import { Toaster, toast } from 'sonner'
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import { ReduxProvider } from '@/redux/ReduxProvider';

const workSans = Work_Sans({
  subsets: ["latin"], // hoặc ["latin", "vietnamese"] nếu cần
  weight: ["400", "500", "600", "700"], // chọn độ dày cần dùng
  variable: "--font-work-sans", // đặt CSS variable để dễ dùng
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased`}
      >
        <Toaster richColors position="top-right" />
        <ReduxProvider>
          <Header />
            {children}
        </ReduxProvider>
          <Footer />
          <ScrollToTopButton />
      </body>
    </html>
  );
}
